### ISSUE TITLE
How to update the top level element?

### ISSUE THREAD

**Issue by alirazaalvi** [ngryman/tree-crawl#12]
I am trying to update the top level element and getting the below error as it is not the children of any element.
Uncaught TypeError: Cannot read property 'children' of undefined

The code i written is

const idToSearch = 1;
const updatedValue = 'updated value';
crawl(records, (node, context) => {
    if (idToSearch.id === node.id) {
      const updatedNode = node;
      updatedNode.name = updatedValue;
      context.parent.children[context.index] = updatedNode; // eslint-disable-line no-param-reassign,max-len
      context.replace(node);
    }
  });

**Comment by ngryman** [comment]
Hey,

Well obviously the root node does not have a parent so the following line fails:
`context.parent.children[context.index] = updatedNode;`

Nothing I can really do here, you have to handle this edge case in your code :)
