### ISSUE TITLE
TypeScript types

### ISSUE THREAD

**Issue by deltaidea** [ngryman/tree-crawl#24]
Hey, this package does exactly what I need!
I'm using TypeScript, and although I can import JS directly, I'd like to have proper types for IntelliSense and stuff.

I'm happy to write the types myself. Would you be willing to integrate them into the repo? It's just an `index.d.ts` file in the root folder.
There're two alternatives: a file in the repo or a separate package `@types/tree-crawl` with that file if you don't want to officially support it.

**Comment by ngryman** [comment]
Hey, an `index.d.ts` and an associated PR would be awesome. Thanks!
