### ISSUE TITLE
Broken main entrypoint

### ISSUE THREAD

**Issue by jaydenseric** [ngryman/tree-crawl#25]
This package does not work in Node.js without an ESM bundling tool like Rollup or Webpack.

The `main` field of `package.json` points to a non-existent `dist/tree-crawl.node.js` file. See [here](https://github.com/ngryman/tree-crawl/blob/v1.0.0/package.json#L8).

Node then falls back to `index.js` which has ESM `import` statements, which causes a crash.

**Comment by jaydenseric** [comment]
Here are the files that install from NPM:

<img width="211" alt="screen shot 2017-06-20 at 3 43 21 pm" src="https://user-images.githubusercontent.com/1754873/27318374-483a6a6e-55cf-11e7-82e5-2ea596603cd1.png">

**Comment by ngryman** [comment]
Oups, good catch. It should be fixed in [v1.0.1](https://github.com/ngryman/tree-crawl/releases/tag/v1.0.1).
