### ISSUE TITLE
get Path like String

### ISSUE THREAD

**Issue by rizr** [ngryman/tree-crawl#72]
Hello, How can I get  string path to node ?
like 'children[3].rows[0]' etc
Thx

**Comment by fpdude** [comment]
@rizr Can you share if you have found a way?

**Comment by rizr** [comment]
@fpdude unfortunately no

**Comment by fpdude** [comment]
@rizr Did you found/know an alternative to tree-crawl, btw? I'm searching for something that can traverse, and generate a new tree structure without mutating the original. Would be very helpful if you know one and share.

**Comment by ngryman** [comment]
Hi @rizr, sorry for the 1+ year later answer. I'm not actively maintaining this project anymore. I'm going to answer anyway, just in case it's useful for you or future visitors.

If you are asking to query a node using a string path, then no, `tree-crawl` doesn't offer a way to do it. It's purposefully a simple traversal library on which you can build more complex features.
To query an object using a string path, you can use [`Lodash#get`](https://lodash.com/docs/4.17.15#get). It does what you want.

**Comment by ngryman** [comment]
Hi @rizr, sorry for the 1+ year later answer. I'm not actively maintaining this project anymore. I'm going to answer anyway, just in case it's useful for you or future visitors.

Your question might be interpreted in two ways.

If you are asking to query a node using a string path, then no, `tree-crawl` doesn't offer a way to do it. It's purposefully a simple traversal library on which you can build more complex features.
To query an object using a string path, you can use [`Lodash#get`](https://lodash.com/docs/4.17.15#get). It does what you want.

If you are asking how to generate such a path while traversing the tree, you can take a look at [this FAQ question](https://github.com/ngryman/tree-crawl#how-can-i-get-the-path-of-the-current-node-37).

**Comment by ngryman** [comment]
@fpdude Your last question seems to be a different issue to me.

You can generate a new tree structure with `tree-crawl`. The API doesn't make it very practical, though. The good news is that I built a higher-level library on top of `tree-crawl` for that purpose. If you're interested, you can take a look at: https://github.com/ngryman/tree-morph.

**Comment by fpdude** [comment]
@ngryman Thanks for the response! I actually ended up using immer's produce function in order to not mutate original tree but will look into tree-morph as well when I have time.

**Comment by fpdude** [comment]
@rizr Had a similar requirement the other day, and this is how I solved it: [CodeSandbox Example](https://codesandbox.io/s/tree-crawl-getpath-c0u3f6). Hope it helps!
